---
cr1-eqiad.wikimedia.org:
  config:
    mgmt_ip: [10.65.0.12/16, 10.65.0.13/16]
    transits:
      192.80.17.185:
        provider: NTT
      2001:418:16::110:
        provider: NTT
      4.16.71.245:
        provider: Lumen
      216.66.30.89:
        provider: "Hurricane Electric"  # Partial transit
      2001:1900:2100::a9d:
        provider: Lumen
      2001:470:0:1c0::1:
        provider: "Hurricane Electric"
    filters:
      xe-3/0/4.1000-in: labs-in
      xe-3/0/4.1102-in: cloud-in
      ae2.1202-in: sandbox
      gr-3/3/0.1-in: border-in
    urpf_strict:
      - xe-3/0/4.1000  # cloud-hosts networks
      - ae1.1030  # analytics1-a-eqiad
      - ae2.1021  # analytics1-b-eqiad
      - ae3.1022  # analytics1-c-eqiad
      - ae4.1023  # analytics1-d-eqiad
    vrrp_bandwidth_threshold: true
    vrrp_master_pinning:
      - ae1  # Row A
      - ae2  # Row B
    capirca:
      - cr-cloud  # For VM traffic
      - cr-sandbox
      - common-loopback
      - cr-border-in
      - cr-labs  # For cloud-hosts servers
    switch_neighbors:
      ssw1-e1-eqiad: {4: 10.66.0.9, 6: 2620:0:861:fe07::2, peer_as: 64810}
      cloudsw1-c8-eqiad: {4: 10.64.147.17, 6: 2620:0:861:fe09::2, peer_as: 64710}

cr2-eqiad.wikimedia.org:
  config:
    mgmt_ip: [10.65.0.14/16, 10.65.0.15/16]
    transits:
      80.239.132.225:
        provider: Arelion
      2001:2000:3080:0a98::1:
        provider: Arelion
    filters:
      xe-1/0/1:0-in4: transport-in  # to eqord
      xe-3/0/4.1100-in: labs-in
      xe-3/0/4.1103-in: cloud-in
      ae2.1202-in: sandbox
      gr-3/3/0.2-in: border-in
    urpf_strict:
      - xe-3/0/4.1100  # cloud-hosts networks
      - ae1.1030  # analytics1-a-eqiad
      - ae2.1021  # analytics1-b-eqiad
      - ae3.1022  # analytics1-c-eqiad
      - ae4.1023  # analytics1-d-eqiad
    damping: [xe-3/2/1]
    vrrp_bandwidth_threshold: true
    vrrp_master_pinning:
      - ae3  # Row C
      - ae4  # Row D
    capirca:
      - cr-cloud  # For VM traffic
      - cr-sandbox
      - common-loopback
      - cr-border-in
      - cr-labs  # For cloud-hosts servers
    switch_neighbors:
      ssw1-f1-eqiad: {4: 10.66.0.11, 6: 2620:0:861:fe08::2, peer_as: 64810}
      cloudsw-d5-eqiad: {4: 10.64.147.15, 6: 2620:0:861:fe0a::2, peer_as: 64710}

cr2-eqord.wikimedia.org:
  config:
    transits:
      192.80.17.197:
        provider: NTT
      2001:418:16::118:
        provider: NTT
      4.53.96.37:
        provider: Lumen
      208.115.136.37:
        provider: "Hurricane Electric"  # Partial transit
      2001:504:0:4::6939:1:
        provider: "Hurricane Electric"
      2001:1900:2100::999:
        provider: Lumen

cr1-codfw.wikimedia.org:
  config:
    mgmt_ip: [10.193.0.10/16, 10.193.0.11/16]
    transits:
      80.239.192.101:
        provider: Arelion
      2001:2000:3080:af4::1:
        provider: Arelion
    filters:
      ae1.2201-in: sandbox
      ae2.2118-in: labs-in
      ae2.2120-in: cloud-in
      xe-1/0/4:0.1000-in: labs-in
      xe-1/0/4:0.1001-in: cloud-in
      xe-1/1/1:2.0-in4: transport-in  # to eqdfw
    urpf_strict:
      - xe-1/0/4:0.1000  # cloud-hosts networks
    damping: [xe-1/0/1:2]
    vrrp_master_pinning:
      - ae1  # Row A
      - ae2  # Row B
    capirca:
      - cr-cloud
      - cr-sandbox
      - common-loopback
      - cr-border-in
      - cr-labs  # For cloud-hosts servers
    switch_neighbors:
      ssw1-a1-codfw: {4: 10.192.254.5, 6: 2620:0:860:132::2, peer_as: 64811}
      cloudsw1-b1-codfw: {4: 10.192.254.1, 6: 2620:0:860:130::2, peer_as: 64711}

cr2-codfw.wikimedia.org:
  config:
    mgmt_ip: [10.193.0.12/16, 10.193.0.13/16]
    transits:
      206.53.202.3:
        provider: "Hurricane Electric"  # Partial transit
      2001:504:61::1b1b:0:1:
        provider: "Hurricane Electric"
      64.156.73.169:
        provider: Lumen
      2001:1900:2100::4b41:
        provider: Lumen
    filters:
      ae1.2201-in: sandbox
      ae2.2118-in: labs-in
      ae2.2120-in: cloud-in
      xe-1/0/4:0.1000-in: labs-in
      xe-1/0/4:0.1001-in: cloud-in
      xe-5/0/0.0-in4: transport-in  # to eqdfw
      xe-1/0/1:1.0-in4: transport-in  # to eqord
    urpf_strict:
      - xe-1/0/4:0.1000  # cloud-hosts networks
    vrrp_master_pinning:
      - ae3  # Row C
      - ae4  # Row D
    primary_ixp: true
    capirca:
      - cr-cloud
      - cr-sandbox
      - common-loopback
      - cr-border-in
      - cr-labs  # For cloud-hosts servers
    switch_neighbors:
      ssw1-a8-codfw: {4: 10.192.254.7, 6: 2620:0:860:133::2, peer_as: 64811}
      cloudsw1-b1-codfw: {4: 10.192.254.3, 6: 2620:0:860:131::2, peer_as: 64711}

cr2-eqdfw.wikimedia.org:
  config:
    transits:
      128.242.179.181:
        provider: NTT
      2001:418:0:5000:0:0:0:3b2:
        provider: NTT
      2001:504:0:5::6939:1:
        provider: "Hurricane Electric"

cr3-ulsfo.wikimedia.org:
  config:
    transits:
      80.239.192.65:
        provider: Arelion
      2001:2000:3080:0a9a::1:
        provider: Arelion
      206.197.187.12:
        provider: "Hurricane Electric"
      2001:504:30::ba00:6939:1:
        provider: "Hurricane Electric"
      4.15.72.113:
        provider: Lumen
      2001:1900:2100::a99:
        provider: Lumen
    filters:
      et-0/0/1.1221-in: sandbox
    primary_ixp: true

cr4-ulsfo.wikimedia.org:
  config:
    transits:
      2001:504:0:1::6939:1:
        provider: "Hurricane Electric"
      2001:418:0:5000::6fa:
        provider: NTT
      129.250.204.5:
        provider: NTT
      206.223.116.37:
        provider: "Hurricane Electric"  # Partial transit
    filters:
      et-0/0/1.1221-in: sandbox

cr1-esams.wikimedia.org:
  config:
    mgmt_ip: [10.80.128.2/17, 10.80.128.4/17]
    transits:
      62.115.179.162:
        provider: Arelion
      2001:2035:0:699::1:
        provider: Arelion
      80.249.209.211:
        provider: "Deutsche Telekom"
      2001:7f8:1::a500:3320:1:
        provider: "Deutsche Telekom"
      2001:7f8:1::a500:6939:1:
        provider: "Hurricane Electric"
    minimum_links:
      ae1: 2

cr2-esams.wikimedia.org:
  config:
    flowspec_flows:
      drop-udp-text-lb:
        description: T243482
        protocol: udp
        destination: 185.15.59.224/32
    transits:
      130.244.6.249:
        provider: Tele2
      2a00:800:0:10::3:1:
        provider: Tele2
      77.109.134.113:
        provider: Init7
      2001:1620:1000::85:
        provider: Init7
      213.46.186.9:
        provider: LibertyGlobal
      2001:730:2209:1::d52e:ba09:
        provider: LibertyGlobal

asw1-bw27-esams.mgmt.esams.wmnet:
  config:
    l3_switch: true
    asn: 4265003001
    capirca:
      - common-loopback
    static_routes:
      185.15.59.231/32:
        next_hop: 185.15.59.2
        description: "ns2.wikimedia.org"
    device_bgp:
      anycast_neighbors:
        dns3004: {4: 185.15.59.2}
        doh3004: {4: 185.15.59.4, 6: 2a02:ec80:300:1:185:15:59:4}
        durum3004: {4: 10.80.0.19, 6: 2a02:ec80:300:101:10:80:0:19}
      lvs_neighbors:
        lvs3008: 10.80.0.3
        lvs3010: 10.80.0.2

asw1-by27-esams.mgmt.esams.wmnet:
  config:
    l3_switch: true
    asn: 4265003002
    capirca:
      - common-loopback
    static_routes:
      185.15.59.231/32:
        next_hop: 185.15.59.34
        description: "ns2.wikimedia.org"
    device_bgp:
      anycast_neighbors:
        dns3003: {4: 185.15.59.34}
        doh3003: {4: 185.15.59.35, 6: 2a02:ec80:300:2:185:15:59:35}
        durum3003: {4: 10.80.1.16, 6: 2a02:ec80:300:102:10:80:1:16}
      lvs_neighbors:
        lvs3009: 10.80.1.14

cr3-eqsin.wikimedia.org:
  config:
    transits:
      62.115.148.76:
        provider: Arelion
        import_policy: true
        export_policy: true
      2001:2000:3080:15b5::1:
        provider: Arelion
        import_policy: true
        export_policy: true
      27.111.228.81:
        provider: "Hurricane Electric"
      2001:de8:4::6939:1:
        provider: "Hurricane Electric"
    filters:
      ae1.530-in: sandbox
      gr-0/0/0.1-in: border-in
    damping: [xe-0/1/0]

cr2-eqsin.wikimedia.org:
  config:
    transits:
      180.87.164.61:
        provider: Tata
        import_policy: true
      2405:2000:800::19:
        provider: Tata
        import_policy: true
      116.51.26.209:
        provider: NTT
        import_policy: true
        export_policy: true
      2001:218:4000:5000:0:0:0:149:
        provider: NTT
        import_policy: true
        export_policy: true
      103.16.102.81:
        provider: "Hurricane Electric"
      2001:de8:12:100::81:
        provider: "Hurricane Electric"
      103.231.152.47:
        provider: "Hurricane Electric"
      2001:df5:b800:bb00::6939:1:
        provider: "Hurricane Electric"
    filters:
      ae1.530-in: sandbox
      gr-0/0/0.2-in: border-in
    primary_ixp: true

cr1-drmrs.wikimedia.org:
  config:
    transits:
      62.115.147.132:
        provider: Arelion
      2001:2035:0:cf1::1:
        provider: Arelion
      80.231.165.54:
        provider: Tata
      2a01:3e0:ff50::3d:
        provider: Tata
      185.1.47.2:
        provider: "Hurricane Electric"
      2001:7f8:36::1b1b:0:1:
        provider: "Hurricane Electric"
    capirca:
      - common-loopback
      - cr-border-in
    filters:
      gr-0/0/0.1-in: border-in

cr2-drmrs.wikimedia.org:
  config:
    transits:
      81.93.217.52:
        provider: NTT
      2001:728:0:5000:0:0:0:164c:
        provider: NTT
      2001:688:0:4::2d1:
        provider: Orange
      193.251.154.145:
        provider: Orange
      37.49.232.13:
        provider: "Hurricane Electric"
      2001:7f8:54:5::13:
        provider: "Hurricane Electric"
    capirca:
      - common-loopback
      - cr-border-in
    filters:
      gr-0/0/0.1-in: border-in

# access switches
asw2-a-eqiad.mgmt.eqiad.wmnet:
  config:
    lldp_disabled: ['ge-8/0/10']

ssw1-e1-eqiad.mgmt.eqiad.wmnet:
  config:
    asn: 64810
    evpn: true
    l3_switch: true
    capirca:
      - common-loopback
    device_bgp:
      cr_neighbors:
        cr1-eqiad: {4: 10.66.0.8, 6: 2620:0:861:fe07::1}

lsw1-e1-eqiad.mgmt.eqiad.wmnet:
  config:
    asn: 64810
    evpn: true
    l3_switch: true
    capirca:
      - common-loopback
      - sw-analytics
    filters:
      irb.1039-in: analytics-in
    device_bgp:
      k8s_dse_neighbors:
        dse-k8s-worker1005: {4: 10.64.130.6, 6: 2620:0:861:109:10:64:130:6}

lsw1-e2-eqiad.mgmt.eqiad.wmnet:
  config:
    asn: 64810
    evpn: true
    l3_switch: true
    capirca:
      - common-loopback
      - sw-analytics
    filters:
      irb.1040-in: analytics-in
    device_bgp:
      k8s_mlserve_neighbors:
        ml-serve1005: {4: 10.64.131.3, 6: 2620:0:861:10a:10:64:131:3}

lsw1-e3-eqiad.mgmt.eqiad.wmnet:
  config:
    asn: 64810
    evpn: true
    l3_switch: true
    capirca:
      - common-loopback
      - sw-analytics
    filters:
      irb.1041-in: analytics-in
    device_bgp:
      k8s_mlserve_neighbors:
        ml-serve1006: {4: 10.64.132.3, 6: 2620:0:861:10b:10:64:132:3}
      k8s_dse_neighbors:
        dse-k8s-worker1006: {4: 10.64.132.8, 6: 2620:0:861:10b:10:64:132:8}

ssw1-f1-eqiad.mgmt.eqiad.wmnet:
  config:
    asn: 64810
    evpn: true
    l3_switch: true
    capirca:
      - common-loopback
    device_bgp:
      cr_neighbors:
        cr1-eqiad: {4: 10.66.0.10, 6: 2620:0:861:fe08::1}

lsw1-f1-eqiad.mgmt.eqiad.wmnet:
  config:
    asn: 64810
    evpn: true
    l3_switch: true
    capirca:
      - common-loopback
      - sw-analytics
    filters:
      irb.1043-in: analytics-in
    device_bgp:
      k8s_dse_neighbors:
        dse-k8s-worker1007: {4: 10.64.134.5, 6: 2620:0:861:10d:10:64:134:5}

lsw1-f2-eqiad.mgmt.eqiad.wmnet:
  config:
    asn: 64810
    evpn: true
    l3_switch: true
    capirca:
      - common-loopback
      - sw-analytics
    filters:
      irb.1044-in: analytics-in
    device_bgp:
      k8s_mlserve_neighbors:
        ml-serve1007: {4: 10.64.135.3, 6: 2620:0:861:10e:10:64:135:3}

lsw1-f3-eqiad.mgmt.eqiad.wmnet:
  config:
    asn: 64810
    evpn: true
    l3_switch: true
    capirca:
      - common-loopback
      - sw-analytics
    filters:
      irb.1045-in: analytics-in
    device_bgp:
      k8s_mlserve_neighbors:
        ml-serve1008: {4: 10.64.136.2, 6: 2620:0:861:10f:10:64:136:2}
      k8s_dse_neighbors:
        dse-k8s-worker1008: {4: 10.64.136.7, 6: 2620:0:861:10f:10:64:136:7}
      k8s_neighbors:
        kubernetes1025: {4: 10.64.136.9, 6: 2620:0:861:10f:10:64:136:9}
        kubernetes1026: {4: 10.64.136.10, 6: 2620:0:861:10f:10:64:136:10}

cloudsw1-c8-eqiad.mgmt.eqiad.wmnet:
  config:
    asn: 64710

cloudsw1-d5-eqiad.mgmt.eqiad.wmnet:
  config:
    asn: 64710
    static_routes:
      10.64.146.251/32:
        next_hop: 10.64.147.11
        description: "cloudsw2-d5-eqiad loopback"
      2620:0:861:11b::251/128:
        next_hop: 2620:0:861:fe11::2
        description: "cloudsw2-d5-eqiad loopback"

cloudsw2-d5-eqiad.mgmt.eqiad.wmnet:
  config:
    asn: 4264710002
    static_routes:
      0.0.0.0/0:
        next_hop: 10.64.147.10
        description: "default via cloudsw1-d5-eqiad"
      ::/0:
        next_hop: 2620:0:861:fe11::1
        description: "default via cloudsw1-d5-eqiad"

cloudsw1-e4-eqiad.mgmt.eqiad.wmnet:
  config:
    asn: 4264710003

cloudsw1-f4-eqiad.mgmt.eqiad.wmnet:
  config:
    asn: 4264710004

cloudsw1-b1-codfw.mgmt.codfw.wmnet:
  config:
    asn: 64711

asw-a-codfw.mgmt.codfw.wmnet:
  config:
    lldp_disabled: ['ge-1/0/47']  # SRXs show L2 errors when receiving LLDP frames

ssw1-a1-codfw.mgmt.codfw.wmnet:
  config:
    asn: 64811
    evpn: true
    l3_switch: true
    capirca:
      - common-loopback
    device_bgp:
      cr_neighbors:
        cr1-codfw: {4: 10.192.254.4, 6: 2620:0:860:132::1}

ssw1-a8-codfw.mgmt.codfw.wmnet:
  config:
    asn: 64811
    evpn: true
    l3_switch: true
    capirca:
      - common-loopback
    device_bgp:
      cr_neighbors:
        cr2-codfw: {4: 10.192.254.6, 6: 2620:0:860:133::1}

lsw1-a1-codfw.mgmt.codfw.wmnet:
  config:
    asn: 64811
    evpn: true
    l3_switch: true
    capirca:
      - common-loopback

lsw1-a2-codfw.mgmt.codfw.wmnet:
  config:
    asn: 64811
    evpn: true
    l3_switch: true
    capirca:
      - common-loopback

lsw1-a3-codfw.mgmt.codfw.wmnet:
  config:
    asn: 64811
    evpn: true
    l3_switch: true
    capirca:
      - common-loopback

lsw1-a4-codfw.mgmt.codfw.wmnet:
  config:
    asn: 64811
    evpn: true
    l3_switch: true
    capirca:
      - common-loopback

lsw1-a5-codfw.mgmt.codfw.wmnet:
  config:
    asn: 64811
    evpn: true
    l3_switch: true
    capirca:
      - common-loopback

lsw1-a6-codfw.mgmt.codfw.wmnet:
  config:
    asn: 64811
    evpn: true
    l3_switch: true
    capirca:
      - common-loopback

lsw1-a7-codfw.mgmt.codfw.wmnet:
  config:
    asn: 64811
    evpn: true
    l3_switch: true
    capirca:
      - common-loopback

lsw1-a8-codfw.mgmt.codfw.wmnet:
  config:
    asn: 64811
    evpn: true
    l3_switch: true
    capirca:
      - common-loopback

lsw1-b2-codfw.mgmt.codfw.wmnet:
  config:
    asn: 64811
    evpn: true
    l3_switch: true
    capirca:
      - common-loopback

lsw1-b3-codfw.mgmt.codfw.wmnet:
  config:
    asn: 64811
    evpn: true
    l3_switch: true
    capirca:
      - common-loopback

lsw1-b4-codfw.mgmt.codfw.wmnet:
  config:
    asn: 64811
    evpn: true
    l3_switch: true
    capirca:
      - common-loopback

lsw1-b5-codfw.mgmt.codfw.wmnet:
  config:
    asn: 64811
    evpn: true
    l3_switch: true
    capirca:
      - common-loopback

lsw1-b6-codfw.mgmt.codfw.wmnet:
  config:
    asn: 64811
    evpn: true
    l3_switch: true
    capirca:
      - common-loopback

lsw1-b7-codfw.mgmt.codfw.wmnet:
  config:
    asn: 64811
    evpn: true
    l3_switch: true
    capirca:
      - common-loopback

lsw1-b8-codfw.mgmt.codfw.wmnet:
  config:
    asn: 64811
    evpn: true
    l3_switch: true
    capirca:
      - common-loopback

asw2-ulsfo.mgmt.ulsfo.wmnet:
  config:
    lldp_disabled: ['ge-1/0/13']  # SRXs show L2 errors when receiving LLDP frames

asw1-eqsin.mgmt.eqsin.wmnet:
  config:
    lldp_disabled: ['ge-0/0/23']  # SRXs show L2 errors when receiving LLDP frames
    mgmt_junos: false  # Remove after upgrade, see T332395

# management switches/routers
mr1-eqiad.wikimedia.org:
  timeout: 120
  config:
    security_zones:
      - name: production
        services: ['ssh', 'ping', 'traceroute', 'snmp', 'ospf', 'ospf3']
        interfaces: ['lo0.0', 'ge-0/0/1.401', 'ge-0/0/1.402']
      - name: untrust
        services: ['ssh', 'ping', 'traceroute']
        interfaces: ['ge-0/0/5.0']
      - name: mgmt
        services: ['ssh', 'ping', 'traceroute', 'dhcp']
        interfaces: ['ge-0/0/0.0']

msw1-eqiad.mgmt.eqiad.wmnet:
  config:
    lldp_disabled: ['ge-0/0/32']  # SRXs show L2 errors when receiving LLDP frames

mr1-codfw.wikimedia.org:
  timeout: 120
  config:
    security_zones:
      - name: production
        services: ['ssh', 'ping', 'traceroute', 'snmp', 'ospf', 'ospf3']
        interfaces: ['lo0.0', 'ge-0/0/1.401', 'ge-0/0/1.402']
      - name: untrust
        services: ['ssh', 'ping', 'traceroute']
        interfaces: ['ge-0/0/5']
      - name: mgmt
        services: ['ssh', 'ping', 'traceroute', 'dhcp']
        interfaces: ['ge-0/0/0.0']

mr1-eqsin.wikimedia.org:
  timeout: 120

msw1-codfw.mgmt.codfw.wmnet:
  config:
    lldp_disabled: ['ge-0/0/32']  # SRXs show L2 errors when receiving LLDP frames

mr1-ulsfo.wikimedia.org:
  timeout: 120

mr1-esams.wikimedia.org:
  timeout: 120
  config:
    security_zones:
      - name: production
        services: ['ssh', 'ping', 'traceroute', 'snmp', 'bgp']
        interfaces: ['lo0.0', 'ge-0/0/3', 'ge-0/0/4']
      - name: untrust
        services: ['ssh', 'ping', 'traceroute']
        interfaces: ['ge-0/0/7']
      - name: mgmt
        services: ['ssh', 'ping', 'traceroute', 'dhcp']
        interfaces: ['irb.900']
    capirca:
      - mr-security-policies

mr1-drmrs.wikimedia.org:
  timeout: 120
  config:
    security_zones:
      - name: production
        services: ['ssh', 'ping', 'traceroute', 'snmp', 'bgp']
        interfaces: ['lo0.0', 'ge-0/0/3', 'ge-0/0/4']
      - name: untrust
        services: ['ssh', 'ping', 'traceroute']
        interfaces: ['ge-0/0/7']
      - name: mgmt
        services: ['ssh', 'ping', 'traceroute', 'dhcp']
        interfaces: ['irb.900']
    capirca:
      - mr-security-policies

asw1-b12-drmrs.mgmt.drmrs.wmnet:
  config:
    l3_switch: true
    asn: 4265006001
    lldp_disabled: ['xe-0/0/44']
    capirca:
      - common-loopback
    device_bgp:
      anycast_neighbors:
        doh6001: {4: 185.15.58.11, 6: 2a02:ec80:600:1:185:15:58:11}
        dns6001: {4: 185.15.58.5}
        durum6001: {4: 10.136.0.21, 6: 2a02:ec80:600:101:10:136:0:21}
      lvs_neighbors:
        lvs6001: 10.136.0.16
        lvs6003: 10.136.0.17

asw1-b13-drmrs.mgmt.drmrs.wmnet:
  config:
    l3_switch: true
    asn: 4265006002
    lldp_disabled: ['xe-0/0/44']
    capirca:
      - common-loopback
    device_bgp:
      anycast_neighbors:
        doh6002: {4: 185.15.58.41, 6: 2a02:ec80:600:2:185:15:58:41}
        dns6002: {4: 185.15.58.37}
        durum6002: {4: 10.136.1.23, 6: 2a02:ec80:600:102:10:136:1:23}
      lvs_neighbors:
        lvs6002: 10.136.1.15
