---
cr1-eqiad.wikimedia.org:
  role: cr
  site: eqiad
  config:
    mgmt_ip: [10.65.0.12/16, 10.65.0.13/16]
    fpcs_to_sample: [3, 4]
    transits:
      192.80.17.185:
        provider: NTT
      2001:418:16::110:
        provider: NTT
      64.125.192.141:
        provider: Zayo
      2001:438:fffd:58::1:
        provider: Zayo
      2001:470:0:1c0::1:
        provider: "Hurricane Electric"
    filters:
      xe-4/2/0.0-in4: transport-in
      xe-4/2/2.12-in4: transport-in
      xe-4/2/2.13-in4: transport-in
      ae1.1030-in: analytics-in
      ae2.1021-in: analytics-in
      ae2.1118-in: labs-in
      ae2.1120-in4: cloud-in
      ae2.1202-in: sandbox
      ae3.1022-in: analytics-in
      ae4.1023-in: analytics-in
      gr-3/3/0.1-in: border-in

cr2-eqiad.wikimedia.org:
  role: cr
  site: eqiad
  config:
    mgmt_ip: [10.65.0.14/16, 10.65.0.15/16]
    fpcs_to_sample: [3, 4]
    transits:
      80.239.132.225:
        provider: Telia
      2001:2000:3080:0a98::1:
        provider: Telia
    filters:
      xe-3/2/3.0-in4: transport-in
      xe-4/1/3.0-in4: transport-in
      xe-4/2/0.0-in4: transport-in
      ae1.1030-in: analytics-in
      ae2.1021-in: analytics-in
      ae2.1118-in: labs-in
      ae2.1120-in4: cloud-in
      ae2.1202-in: sandbox
      ae3.1022-in: analytics-in
      ae4.1023-in: analytics-in
      gr-4/3/0.2-in: border-in
    damping: [xe-3/2/3, xe-4/1/3]

cr2-eqord.wikimedia.org:
  role: cr
  site: eqord
  config:
    fpcs_to_sample: [0]
    transits:
      192.80.17.197:
        provider: NTT
      2001:418:16::118:
        provider: NTT
      208.185.240.45:
        provider: Zayo
      2001:438:fffd:56::1:
        provider: Zayo
      2001:504:0:4::6939:1:
        provider: "Hurricane Electric"
    netbox_driven_interfaces: false  # Hopefully T258942

cr1-codfw.wikimedia.org:
  role: cr
  site: codfw
  config:
    mgmt_ip: [10.193.0.10/16, 10.193.0.11/16]
    fpcs_to_sample: [5]
    transits:
      80.239.192.101:
        provider: Telia
      2001:2000:3080:af4::1:
        provider: Telia
    filters:
      xe-5/0/0.0-in4: transport-in
      xe-5/0/2.0-in4: transport-in
      xe-5/1/2.0-in4: transport-in
      xe-5/2/1.0-in4: transport-in
      ae2.2120-in: cloud-in
      ae1.2201-in: sandbox
    damping: [xe-5/0/2, xe-5/1/2]
    netbox_driven_interfaces: false  # Hopefully T258942

cr2-codfw.wikimedia.org:
  role: cr
  site: codfw
  config:
    mgmt_ip: [10.193.0.12/16, 10.193.0.13/16]
    fpcs_to_sample: [5]
    transits:
      64.125.129.69:
        provider: Zayo
      2001:438:fffd:5c::1:
        provider: Zayo
    filters:
      ae1.2201-in: sandbox
      ae2.2120-in: cloud-in
      xe-5/0/0.0-in4: transport-in
      xe-5/0/1.0-in4: transport-in
      xe-5/2/1.0-in4: transport-in
    damping: [xe-5/0/1]

cr2-eqdfw.wikimedia.org:
  role: cr
  site: eqdfw
  config:
    fpcs_to_sample: [0]
    transits:
      128.242.179.181:
        provider: NTT
      2001:418:0:5000:0:0:0:3b2:
        provider: NTT
      2001:504:0:5::6939:1:
        provider: "Hurricane Electric"

cr3-ulsfo.wikimedia.org:
  role: cr
  site: ulsfo
  config:
    fpcs_to_sample: [0]
    transits:
      80.239.192.65:
        provider: Telia
      2001:2000:3080:0a9a::1:
        provider: Telia
      209.133.4.57:
        provider: Zayo
      2001:438:fffd:57::1:
        provider: Zayo
    filters:
      et-0/0/1.1221-in: sandbox
    netbox_driven_interfaces: false  # Hopefully T258942
    prioritize_peering: true  # T259614

cr4-ulsfo.wikimedia.org:
  role: cr
  site: ulsfo
  config:
    fpcs_to_sample: [0]
    transits:
      2001:504:d::10:
        provider: "Hurricane Electric"
      2001:418:0:5000::6fa:
        provider: NTT
      129.250.204.5:
        provider: NTT
    filters:
      et-0/0/1.1221-in: sandbox
    damping: [xe-0/1/2]
    prioritize_peering: true  # T259614

cr3-esams.wikimedia.org:
  role: cr
  site: esams
  config:
    mgmt_ip: [10.21.0.119/24, 10.21.0.120/24]
    fpcs_to_sample: [0]
    transits:
      62.115.145.24:
        provider: Telia
      2001:2000:3080:0ee8::1:
        provider: Telia
    filters:
      ae1.102-in: sandbox
      ae1.401-in4: transport-in
      gr-0/0/0.2-in: border-in

cr2-esams.wikimedia.org:
  role: cr
  site: esams
  config:
    mgmt_ip: [10.21.0.117/24, 10.21.0.118/24]
    fpcs_to_sample: [0]
    transits:
      80.249.209.211:
        provider: "Deutsche Telekom"
      2001:7f8:1::a500:3320:1:
        provider: "Deutsche Telekom"
      87.255.35.65:
        provider: FiberRing
      2a00:ec8::21d:
        provider: FiberRing
      2001:7f8:1::a500:6939:1:
        provider: "Hurricane Electric"
    filters:
      ae1.102-in: sandbox
      ae1.403-in4: transport-in
      gr-0/1/0.2-in: border-in
    minimum_links:
      ae2: 2

cr3-knams.wikimedia.org:
  role: cr
  site: knams
  config:
    fpcs_to_sample: [0]
    flowspec_flows:
      drop-udp-text-lb:
        description: T243482
        protocol: udp
        destination: 91.198.174.192/32
    transits:
      130.244.6.249:
        provider: Tele2
      2a00:800:0:10::3:1:
        provider: Tele2
      77.109.134.113:
        provider: Init7
      2001:1620:1000::85:
        provider: Init7
      78.41.155.33:
        provider: Datahop
      2a01:450:2::1:1:
        provider: Datahop
      213.46.186.9:
        provider: LibertyGlobal
      2001:730:2209:1::d52e:ba09:
        provider: LibertyGlobal

cr3-eqsin.wikimedia.org:
  role: cr
  site: eqsin
  config:
    fpcs_to_sample: [0]
    transits:
      62.115.148.76:
        provider: Telia
        import_policy: true
        export_policy: true
      2001:2000:3080:15b5::1:
        provider: Telia
        import_policy: true
        export_policy: true
    netbox_driven_interfaces: false  # Hopefully T258942
    filters:
      ae1.530-in: sandbox
      gr-0/0/0.1-in: border-in
    damping: [xe-0/1/0]

cr2-eqsin.wikimedia.org:
  role: cr
  site: eqsin
  config:
    fpcs_to_sample: [0]
    transits:
      180.87.164.61:
        provider: Tata
      2405:2000:800::19:
        provider: Tata
      116.51.26.209:
        provider: NTT
        import_policy: true
        export_policy: true
      2001:218:4000:5000:0:0:0:149:
        provider: NTT
        import_policy: true
        export_policy: true
    filters:
      ae1.530-in: sandbox
      gr-0/0/0.2-in: border-in

# access switches
asw2-a-eqiad.mgmt.eqiad.wmnet:
  role: asw
  site: eqiad
  config:
    lldp_disabled: ['ge-8/0/10']

asw2-b-eqiad.mgmt.eqiad.wmnet:
  role: asw
  site: eqiad

asw2-c-eqiad.mgmt.eqiad.wmnet:
  role: asw
  site: eqiad

asw2-d-eqiad.mgmt.eqiad.wmnet:
  role: asw
  site: eqiad

asw-a-codfw.mgmt.codfw.wmnet:
  role: asw
  site: codfw
  config:
    lldp_disabled: ['ge-1/0/47']  # SRXs show L2 errors when receiving LLDP frames

asw-b-codfw.mgmt.codfw.wmnet:
  role: asw
  site: codfw

asw-c-codfw.mgmt.codfw.wmnet:
  role: asw
  site: codfw

asw-d-codfw.mgmt.codfw.wmnet:
  role: asw
  site: codfw

asw2-esams.mgmt.esams.wmnet:
  role: asw
  site: esams
  config:
    lldp_disabled: ['ge-5/0/47']  # SRXs show L2 errors when receiving LLDP frames
    netbox_driven_interfaces: true

asw2-ulsfo.mgmt.ulsfo.wmnet:
  role: asw
  site: ulsfo
  config:
    lldp_disabled: ['ge-1/0/13']  # SRXs show L2 errors when receiving LLDP frames
    netbox_driven_interfaces: true

asw1-eqsin.mgmt.eqsin.wmnet:
  role: asw
  site: eqsin
  config:
    lldp_disabled: ['ge-0/0/23']  # SRXs show L2 errors when receiving LLDP frames
    netbox_driven_interfaces: true

# management switches/routers
mr1-eqiad.wikimedia.org:
  role: mr
  site: eqiad
  config:
    security_zones:
      - name: production
        services: ['ssh', 'ping', 'traceroute', 'snmp', 'ospf', 'ospf3']
        interfaces: ['lo0.0', 'ge-0/0/1.401', 'ge-0/0/1.402']
      - name: untrust
        services: ['ssh', 'ping', 'traceroute']
        interfaces: ['ge-0/0/5.0']
      - name: mgmt
        services: ['ssh', 'ping', 'traceroute']
        interfaces: ['ge-0/0/0.0']
      - name: access
        services: ['ssh', 'ping', 'traceroute', 'dhcp']
        interfaces: ['ge-0/0/2.0']
    dhcp_pool: 10.66.0.0/24
    els: false  # Legacy Junos syntax

msw1-eqiad.mgmt.eqiad.wmnet:
  role: msw
  site: eqiad
  config:
    lldp_disabled: ['ge-0/0/32']  # SRXs show L2 errors when receiving LLDP frames

mr1-codfw.wikimedia.org:
  role: mr
  site: codfw
  config:
    security_zones:
      - name: production
        services: ['ssh', 'ping', 'traceroute', 'snmp', 'ospf', 'ospf3']
        interfaces: ['lo0.0', 'ge-0/0/1.401', 'ge-0/0/1.402']
      - name: untrust
        services: ['ssh', 'ping', 'traceroute']
        interfaces: ['ge-0/0/5']
      - name: mgmt
        services: ['ssh', 'ping', 'traceroute']
        interfaces: ['ge-0/0/0.0']
      - name: access
        services: ['ssh', 'ping', 'traceroute', 'dhcp']
        interfaces: []  # Keeping the zone just in case to not delete policies, was ge-0/0/2.0

mr1-eqsin.wikimedia.org:
  role: mr
  site: eqsin
  config:
    els: false  # Legacy Junos syntax

msw1-codfw.mgmt.codfw.wmnet:
  role: msw
  site: codfw
  config:
    lldp_disabled: ['ge-0/0/32']  # SRXs show L2 errors when receiving LLDP frames

mr1-ulsfo.wikimedia.org:
  role: mr
  site: ulsfo
  config:
    els: false  # Legacy Junos syntax

mr1-esams.wikimedia.org:
  role: mr
  site: esams
  config:
    security_zones:
      - name: production
        services: ['ssh', 'ping', 'traceroute', 'snmp', 'ospf', 'ospf3']
        interfaces: ['lo0.0', 'ge-0/0/1.402', 'ge-0/0/1.404']
      - name: untrust
        services: ['ssh', 'ping', 'traceroute']
        interfaces: ['ge-0/0/6.2484']
      - name: mgmt
        services: ['ssh', 'ping', 'traceroute']
        interfaces: ['irb.900']
      - name: access
        services: ['ssh', 'ping', 'traceroute', 'dhcp']
        interfaces: []  # Keeping the zone just in case to not delete policies, was ge-0/0/2.0
      - name: customers
        services: ['ping', 'traceroute']
        interfaces: ['ge-0/0/6.2483']
        screen: untrust-screen

# TODO: payments firewall
# pfw-eqiad.wikimedia.org:
#   role: pfw
#   site: eqiad

# pfw-codfw.wikimedia.org:
#   role: pfw
#   site: codfw


# Example core router configuration block:
#
# cr9-foobar.wikimedia.org:
#   role: cr
#   site: foobar
#   config:
#      fpcs_to_sample: [0] [Optional] List of FPC indices on which to enable jflow sampling
#      mgmt_ip: [Optional] List of addr/netmask for mgmt interfaces; if specified, one per RE
#        - 10.1.2.3/16
#        - 10.1.2.4/16
#      transits:
#        192.0.0.1:  [Unique] (or v6) BGP peer IP
#          provider: NTT  [Required] one of common.yaml transit_providers
#          import_policy: true [Optional] Generate the policy based on the peer ASN
#          export_policy: true [Optional] Generate the policy based on the peer ASN
#          disabled: true [optional]
#      vrrp_priority: 90 [Optional] Override priority for every VRRP, useful for forced failover/maintenance
#                                   Highest number wins; default when unspecified is 100.
#      damping: [xe-0/1/0] [Optional] Enable interface flap damping
#      netbox_driven_interfaces: true [Optional] Generate interfaces config based on Netbox data
#      tunnels:  [Optional]  GRE tunnels source/destination
#        gr-0/0/0.1:  # description
#          source: 10.1.2.3
#          destination: 10.3.2.1
#       filters:  [Optional] Extra firewall filters to apply to interfaces
#         ae1.530-in: foo    Apply foo as input to both inet and inet6 (if any)
#         ae1.530-in4: foo   Apply foo as input only to inet (even if inet6 exists)
#         gr-0/0/0.2-out: bar   Apply bar as output to both inet and inet6
#       minimum_links:  [Optional] For AE interfaces only
#         ae2: 2   # Take the interface down if the bundle doesn't have at least 2 healthy members
