---
eqiad:
  confed: 65001
  mgmt_gw: 10.65.0.1
  customers:
    - 64601  # k8s-eqiad
    - 64603  # k8s-staging-eqiad
    - 64606  # k8s-mlserve-eqiad
    - 64609  # k8s-dse-eqiad
    - 64610  # k8s-aux-eqiad
    - 64613  # k8s-dse-codfw
    - 64700  # fundraising-eqiad
    - 64710  # WMCS-eqiad
  bgp_out:
    208.80.154.0/23: BGP_aggregate_contributors  # eqiad
    198.35.27.0/24: BGP_from_anycast  # Anycast
    185.71.138.0/24: BGP_from_anycast  # Wikidough Anycast
  bgp6_out:
    2620:0:861::/48: BGP_aggregate_contributors  # eqiad
    2001:67c:930::/48: BGP_from_anycast  # Wikidough Anycast v6
  ping_offload_vip: 208.80.154.224/32
  ping_offload_redirect: 10.64.32.63  # ping1004.eqiad.wmnet
  sampling:
    collectors:
      netflow1002: 10.64.16.82
  dhcp_server:
    name: install1004
    ip: 208.80.154.74
  dhcp_relay_ra:
    - ae1.1001
    - ae1.1017
    - ae1.1030
    - ae1.1117
    - ae2.1002
    - ae2.1018
    - ae2.1021
    - ae3.1003
    - ae3.1019
    - ae3.1022
    - ae3.1119
    - ae4.1023
    - ae4.1020
    - ae4.1004
    - ae2.1202
  tcp_mss_clamping: true
  prepend_as_out: false
  ibgp_clusters:
    "64810":
      evpn: true
      pods:
        ef:
          rr:
            - ssw1-e1-eqiad
            - ssw1-f1-eqiad
          client:
            - lsw1-e1-eqiad
            - lsw1-e2-eqiad
            - lsw1-e3-eqiad
            - lsw1-e5-eqiad
            - lsw1-e6-eqiad
            - lsw1-e7-eqiad
            - lsw1-e8-eqiad
            - lsw1-f1-eqiad
            - lsw1-f2-eqiad
            - lsw1-f3-eqiad
            - lsw1-f5-eqiad
            - lsw1-f6-eqiad
            - lsw1-f7-eqiad
            - lsw1-f8-eqiad
    "64814":
      evpn: true
      pods:
        cd:
          rr:
            - ssw1-d1-eqiad
            - ssw1-d8-eqiad
          client:
            - lsw1-c2-eqiad
            - lsw1-c3-eqiad
            - lsw1-c4-eqiad
            - lsw1-c5-eqiad
            - lsw1-c6-eqiad
            - lsw1-c7-eqiad
            - lsw1-d1-eqiad
            - lsw1-d2-eqiad
            - lsw1-d3-eqiad
            - lsw1-d4-eqiad
            - lsw1-d6-eqiad
            - lsw1-d7-eqiad
            - lsw1-d8-eqiad
    "64710":
      evpn: false
      pods:
        cloud:
          rr:
            - cloudsw1-c8-eqiad
            - cloudsw1-d5-eqiad
          client:
            - cloudsw1-e4-eqiad
            - cloudsw1-f4-eqiad

eqord:
  confed: 65020
  bgp_out:
    208.80.152.0/23: BGP_agg_net_pops  # codfw
    208.80.154.0/23: BGP_agg_net_pops  # eqiad
    198.35.27.0/24: BGP_agg_net_pops  # ns2 Anycast
    185.71.138.0/24: BGP_agg_net_pops  # Wikidough Anycast
  bgp6_out:
    2620:0:860::/48: BGP_agg_net_pops  # codfw
    2620:0:861::/48: BGP_agg_net_pops  # eqiad
    2001:67c:930::/48: BGP_agg_net_pops  # Wikidough Anycast v6
  sampling:
    collectors:
      netflow1002: 10.64.16.82
  tcp_mss_clamping: true
  prepend_as_out: false

codfw:
  confed: 65002
  mgmt_gw: 10.193.0.1
  customers:
    - 64602  # k8s-codfw
    - 64604  # k8s-staging-codfw
    - 64607  # k8s-mlserve-codfw
    - 64608  # k8s-mlstaging-codfw
    - 64611  # k8s-aux-codfw
    - 64612  # Ganeti
    - 64701  # fundraising-codfw
    - 64711  # WMCS-codfw
  bgp_out:
    208.80.152.0/23: BGP_aggregate_contributors  # codfw
    185.15.57.0/24: BGP_from_customers  # customers/wmcs
    198.35.27.0/24: BGP_from_anycast  # ns2 Anycast
    185.71.138.0/24: BGP_from_anycast  # Wikidough Anycast
  bgp6_out:
    2620:0:860::/48: BGP_aggregate_contributors  # codfw
    2001:67c:930::/48: BGP_from_anycast  # Wikidough Anycast v6
  ping_offload_vip: 208.80.153.224/32
  ping_offload_redirect: 10.192.48.9  # ping2004.codfw.wmnet
  sampling:
    collectors:
      netflow2003: 10.192.32.159
  dhcp_server:
    name: install2004
    ip: 208.80.153.105
  prepend_as_out: false
  ibgp_clusters:
    "64811":
      evpn: true
      pods:
        ab:
          rr:
            - ssw1-a1-codfw
            - ssw1-a8-codfw
          client:
            - lsw1-a2-codfw
            - lsw1-a3-codfw
            - lsw1-a4-codfw
            - lsw1-a5-codfw
            - lsw1-a6-codfw
            - lsw1-a7-codfw
            - lsw1-a8-codfw
            - lsw1-b2-codfw
            - lsw1-b3-codfw
            - lsw1-b4-codfw
            - lsw1-b5-codfw
            - lsw1-b6-codfw
            - lsw1-b7-codfw
            - lsw1-b8-codfw
        cd:
          rr:
            - ssw1-d1-codfw
            - ssw1-d8-codfw
          client:
            - lsw1-c1-codfw
            - lsw1-c2-codfw
            - lsw1-c3-codfw
            - lsw1-c4-codfw
            - lsw1-c5-codfw
            - lsw1-c6-codfw
            - lsw1-c7-codfw
            - lsw1-d1-codfw
            - lsw1-d2-codfw
            - lsw1-d3-codfw
            - lsw1-d4-codfw
            - lsw1-d5-codfw
            - lsw1-d6-codfw
            - lsw1-d7-codfw
            - lsw1-d8-codfw
    "64813":
      evpn: false
      pods:
        ef:
          rr:
            - ssw1-e1-codfw
            - ssw1-f1-codfw
          client:
            - lsw1-e1-codfw
            - lsw1-e2-codfw
            - lsw1-e3-codfw
            - lsw1-e4-codfw
            - lsw1-e5-codfw
            - lsw1-f1-codfw
            - lsw1-f2-codfw
            - lsw1-f3-codfw
            - lsw1-f4-codfw

eqdfw:
  confed: 65002
  bgp_out:
    198.35.27.0/24: BGP_from_anycast  # ns2 Anycast
    208.80.152.0/23: BGP_agg_net_pops  # codfw
    185.15.57.0/24: BGP_aggregate_contributors  # WMCS codfw
    185.71.138.0/24: BGP_from_anycast  # Wikidough Anycast
  bgp6_out:
    2620:0:860::/48: BGP_agg_net_pops  # codfw
    2001:67c:930::/48: BGP_from_anycast  # Wikidough Anycast v6
  sampling:
    collectors:
      netflow2003: 10.192.32.159
  prepend_as_out: false

ulsfo:
  confed: 65004
  mgmt_gw: 10.128.128.1
  bgp_out:
    198.35.26.0/24: BGP_aggregate_contributors  # ulsfo
    198.35.27.0/24: BGP_from_anycast  # ns2 Anycast
    185.71.138.0/24: BGP_from_anycast  # Wikidough Anycast
  bgp6_out:
    2620:0:863::/48: BGP_aggregate_contributors  # ulsfo
    2001:67c:930::/48: BGP_from_anycast  # Wikidough Anycast v6
  sampling:
    collectors:
      netflow4002: 10.128.0.13
  dhcp_server:
    name: install4003
    ip: 198.35.26.11
  dhcp_relay_ra:
    - et-0/0/1.1201
    - et-0/0/1.1211
    - et-0/0/1.1221
  prepend_as_out: false

eqsin:
  confed: 65005
  mgmt_gw: 10.132.128.1
  bgp_out:
    103.102.166.0/24: BGP_aggregate_contributors  # eqsin
    198.35.27.0/24: BGP_from_anycast  # ns2 Anycast
    185.71.138.0/24: BGP_from_anycast  # Wikidough Anycast
  bgp6_out:
    2001:df2:e500::/48: BGP_aggregate_contributors  # eqsin
    2001:67c:930::/48: BGP_from_anycast  # Wikidough Anycast v6
  sampling:
    collectors:
      netflow5002: 10.132.0.15
  dhcp_server:
    name: install5002
    ip: 103.102.166.12
  dhcp_relay_ra:
    - ae1.510
    - ae1.520
    - ae1.530
  tcp_mss_clamping: true
  prepend_as_out: false

esams:
  confed: 65003
  mgmt_gw: 10.80.128.1
  bgp_out:
    185.15.59.0/24: BGP_aggregate_contributors  # esams
    198.35.27.0/24: BGP_from_anycast  # ns2 Anycast
    185.71.138.0/24: BGP_from_anycast  # Wikidough Anycast
  bgp6_out:
    2a02:ec80:300::/48: BGP_aggregate_contributors  # esams
    2001:67c:930::/48: BGP_from_anycast  # Wikidough Anycast v6
  dhcp_server:
    name: install3003
    ip: 185.15.59.3
  sampling:
    collectors:
      netflow3003: 10.80.0.15
  prepend_as_out: false

drmrs:
  confed: 65006
  mgmt_gw: 10.136.128.1
  bgp_out:
    185.15.58.0/24: BGP_aggregate_contributors  # drmrs
    185.71.138.0/24: BGP_from_anycast  # Wikidough Anycast
    198.35.27.0/24: BGP_from_anycast  # ns2 Anycast
  bgp6_out:
    2a02:ec80:600::/48: BGP_aggregate_contributors  # drmrs
    2001:67c:930::/48: BGP_from_anycast  # Wikidough Anycast v6
  sampling:
    collectors:
      netflow6001: 10.136.1.22
  tcp_mss_clamping: true
  dhcp_server:
    name: install6002
    ip: 185.15.58.12
  prepend_as_out: false

magru:
  confed: 65007
  mgmt_gw: 10.140.128.1
  bgp_out:
    195.200.68.0/24: BGP_aggregate_contributors  # magru
    185.71.138.0/24: BGP_from_anycast  # Wikidough Anycast
    198.35.27.0/24: BGP_from_anycast  # ns2 Anycast
  bgp6_out:
    2a02:ec80:700::/48: BGP_aggregate_contributors  # magru
    2001:67c:930::/48: BGP_from_anycast  # Wikidough Anycast v6
  sampling:
    collectors:
      netflow7002: 10.140.2.6
  dhcp_server:
    name: install7002
    ip: 195.200.68.100
  prepend_as_out: false
  customers:
    - 64612  # Ganeti
